name: CSI2115 check if Linux kernel compiles

on: 
  push:
    paths:
      - 'linux'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Get current commit id
      run: |
        echo "commit_id="`git rev-parse --short HEAD:linux` >> $GITHUB_ENV
    - name: Install required dependencies
      shell: bash
      run: |
        ./install-deps.sh
    - name: Download linux from my repository
      shell: bash
      run: wget "https://github.com/PetrasRec/linux/archive/${{ env.commit_id }}.zip" -O newLinuxOS.zip
    - name: Unzip downloaded files
      shell: bash
      run: |
        sudo apt-get install unzip
        unzip newLinuxOS.zip -d newLinuxOS
    - name: Build linux kernel
      shell: bash
      run: ./build-linux.sh newLinuxOS/linux-`git rev-parse HEAD:linux` tinyconfig

