name: CSI2115 Linux kernel

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Go to linux dir
      shell: bash
      run: cd linux
    - name: Check files
      shell: bash
      run: |
        ls
    - name: Clone linux OS
      shell: bash
      run: |
        wget "https://github.com/PetrasRec/linux/archive/"`git rev-parse --short HEAD`".zip"
