name: CSI2115 Linux kernel compilation 

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Check current commit id
      run: |
        echo "current_commit_id="`git rev-parse --short HEAD:linux` >> $GITHUB_ENV
    - name: Check commit number
      run: |
        if [ "${{ env.commit_id }}" != "${{ env.current_commit_id }}" ]
        then
          echo "commit_id=${{ env.current_commit_id }}" >> $GITHUB_ENV
        fi
    - name: Install Dependencies
      shell: bash
      run: |
        ./install-deps.sh
    - name: Download linux
      shell: bash
      run: wget "https://github.com/PetrasRec/linux/archive/${{ env.commit_id }}.zip" -O newLinuxOS.zip
    - name: Unzip linux
      shell: bash
      run: |
        sudo apt-get install unzip
        unzip newLinuxOS.zip -d newLinuxOS
    - name: Build linux
      shell: bash
      run: ./build-linux.sh newLinuxOS/linux-"${{ env.commit_id }}"" tinyconfig

