name: CSI2115 Linux kernel compilation check

on: 
  push:
    paths:
      - 'linux/**'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04
dispatch:
    steps:
    - uses: actions/checkout@v2
    - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: PetrasRec/Linux
          event-type: RepoAevent
    - name: Install Dependencies
      shell: bash
      run: |
        ./install-deps.sh
    - name: Download linux
      shell: bash
      run: wget "https://github.com/PetrasRec/linux/archive/"`git rev-parse --short HEAD:linux`".zip" -O newLinuxOS.zip
    - name: Unzip linux
      shell: bash
      run: |
        sudo apt-get install unzip
        unzip newLinuxOS.zip -d newLinuxOS
    - name: Build linux
      shell: bash
      run: ./build-linux.sh newLinuxOS/linux-`git rev-parse HEAD:linux` tinyconfig

