name: CSI2115 Linux kernel

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Go to linux rep
      shell: bash
      run: cd linux
    - name: Save commit id
      shell: bash
      run: |
        wget "https://github.com/PetrasRec/linux/archive/"`git rev-parse --short HEAD`".zip -O .."
    - name: Come back to scripts directory
      shell: bash
      run: echo `cd .. && ls`

