name: CSI2115 Linux kernel

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Go to linux repository
      shell: bash
      run: cd linux
    - name: Save commit id
      shell: bash
      run: echo '##vso[task.setvariable variable=commit_id]`git rev-parse --short HEAD`'
    - name: Come back to scripts directory
      shell: bash
      run: cd ..
    - name: Clone linux OS
      shell: bash
      run: |
        wget "https://github.com/PetrasRec/linux/archive/"${commit_id}}".zip"
