name: CSI2115 Linux kernel

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Download linux
      shell: bash
      run: wget "https://github.com/PetrasRec/linux/archive/"`git rev-parse --short HEAD:linux`".zip" -O newLinuxOS.zip
    - name: Unzip linux
      shell: bash
      run: |
        sudo apt-get install unzip
        unzip newLinuxOS.zip -d newLinuxOS  

