name: Testing linux kernel

on: 
  push:
    paths:
      - 'test/**'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Test the scripts repo
      shell: bash
      run: |
        make -C test
        ./test/example/example.exe

